spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-flyway?autoReconnect=true&useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
#      connection-timeout: 15000
#      maximum-pool-size: 3
#logging:
#  level:
#    com.zaxxer.hikari: debug
